name: Build Test
on:
  push:
    branches: [ "*" ]
    paths-ignore:
        - "**/**.md"
        - ".*"
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        build_type: [RELEASE, DEBUG]
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Vulkan
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
          install_runtime: true
          cache: true
          stripdown: true
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install libwayland-dev glslang-dev libxkbcommon-dev libvulkan-dev
    - name: Build
      run: make ${{ matrix.build_type }}=on
