name: Build Test
on:
  push:
    branches: [ "*" ]
    paths-ignore:
        - "**/**.md"
        - ".*"
  pull_request:
    branches: [ "*" ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        build_type: [Release, Debug]
        compiler: [gcc]
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Vulkan
      uses: jakoch/install-vulkan-sdk-action@v1
      with:
          install_runtime: true
          cache: true
          stripdown: true
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install libwayland-dev glslang-dev
    - name: Configure
      run: cmake -B ${{ github.workspace }}/buildDirectory -DCMAKE_C_COMPILER=${{ matrix.compiler }} -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} -S ${{ github.workspace }} -DWATERLILY_UPDATE_MODULES=ON
    - name: Build
      run: cmake --build ${{ github.workspace }}/buildDirectory --config ${{ matrix.build_type }} --parallel 9
